### ISSUE TITLE
Pseudo-code Models

### ISSUE THREAD

**Issue by luketeal** [luketeal/farmerFresh#1]
We mostly just need an idea of the data set and relationships - this will likely go hand-in-hand with the wireframe

**Comment by swethareddyl** [comment]
[https://docs.google.com/document/d/1oPY2j4YciMFqiFY_mZeu0eLtKS5Bax8K-Gasitll0DQ/edit?usp=sharing](url)

**Comment by swethareddyl** [comment]
Hope it helps for you guys.

**Comment by luketeal** [comment]
I think you need to adjust the link so that we can view it
